//==========================
// File: data_memory.v
// Description: Byte-addressable data RAM for RV32I processor.
//              Supports byte (8-bit), halfword (16-bit) and word (32-bit)
//              reads and writes.  Write strobes are generated by the
//              load_store_unit and applied on the rising clock edge.
//              Reads are combinatorial (single-cycle design).
// Author      : RTL Design Example
//==========================

`timescale 1ns/1ps
`default_nettype none

module data_memory #(
    parameter XLEN      = 32,          // Data/address width
    parameter MEM_DEPTH = 1024,        // Depth in bytes
    parameter HEX_FILE  = "data.hex"   // Optional initial data (use "" to skip)
)(
    input  wire             clk,       // System clock
    input  wire             rst_n,     // Active-LOW reset (unused for RAM, kept for interface consistency)

    // ----- Write port -----
    input  wire [XLEN-1:0]  addr,      // Byte address
    input  wire [XLEN-1:0]  wdata,     // Write data (full 32-bit word; byte sel picks active bytes)
    input  wire [3:0]       byte_en,   // Byte-enable strobes: [3]=byte3 … [0]=byte0
    input  wire             mem_wen,   // Write-enable (1 = write this cycle)

    // ----- Read port -----
    output wire [XLEN-1:0]  rdata      // Raw 32-bit read data (sign/zero extension done in LSU)
);

    // -----------------------------------------------------------------------
    // Memory array – byte-wide for correct partial writes
    // -----------------------------------------------------------------------
    reg [7:0] mem [0:MEM_DEPTH-1];

    integer i;

    // -----------------------------------------------------------------------
    // Initialise from hex file (optional)
    // -----------------------------------------------------------------------
    initial begin
        // Zero-init first, then overwrite with file contents
        for (i = 0; i < MEM_DEPTH; i = i + 1)
            mem[i] = 8'h00;
        if (HEX_FILE != "")
            $readmemh(HEX_FILE, mem);
    end

    // -----------------------------------------------------------------------
    // Synchronous byte-granule write
    // -----------------------------------------------------------------------
    always @(posedge clk) begin
        if (mem_wen) begin
            if (byte_en[0]) mem[addr + 0] <= wdata[ 7: 0];
            if (byte_en[1]) mem[addr + 1] <= wdata[15: 8];
            if (byte_en[2]) mem[addr + 2] <= wdata[23:16];
            if (byte_en[3]) mem[addr + 3] <= wdata[31:24];
        end
    end

    // -----------------------------------------------------------------------
    // Combinatorial word-wide read (little-endian assembly)
    // -----------------------------------------------------------------------
    assign rdata = { mem[addr+3], mem[addr+2], mem[addr+1], mem[addr+0] };

endmodule

`default_nettype wire
